name: Handle Issues
on:
  issues:
    types: [opened, edited, closed]
    branches:
      - main
      - master
jobs:
  output-info:
    runs-on: ubuntu-latest
   
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
