name: HAndle Issues
on:
  issues:
    types: [opened, edited, closed]   
jobs:
  output-info:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Output events
        run: echo "${{ toJSON(github.event) }}"

